### ISSUE TITLE
PanamaTensorOperations.accumulate throws UnsupportedOperationException on mac m1 pro

### ISSUE THREAD

**Issue by jolivares** [tjake/Jlama#101]
I got `java.lang.UnsupportedOperationException` when running `jlama chat`

```
$ jbang run jlama@tjake chat tjake/Llama-3.2-1B-Instruct-JQ4 --auto-download
WARNING: Using incubator modules: jdk.incubator.vector
Using Native SIMD Operations (OffHeap)
Model type = Q4, Working memory type = F32, Quantized memory type = I8

Chatting with tjake/Llama-3.2-1B-Instruct-JQ4...


You: hi

Jlama: Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.github.tjake.jlama.cli.commands.ChatCommand@4b2bac3f): java.lang.UnsupportedOperationException
	at picocli.CommandLine.executeUserObject(CommandLine.java:2035)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2264)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2664)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:2599)
	at com.github.tjake.jlama.cli.JlamaCli.main(JlamaCli.java:57)
	at jlama.main(jlama.java:22)
Caused by: java.lang.UnsupportedOperationException
	at com.github.tjake.jlama.tensor.operations.PanamaTensorOperations.accumulate(PanamaTensorOperations.java:2170)
	at com.github.tjake.jlama.tensor.operations.NativeTensorOperations.accumulate(NativeTensorOperations.java:409)
	at com.github.tjake.jlama.model.TransformerBlock.forward(TransformerBlock.java:182)
	at com.github.tjake.jlama.model.AbstractModel.forward(AbstractModel.java:293)
	at com.github.tjake.jlama.model.AbstractModel.batchForward(AbstractModel.java:280)
	at com.github.tjake.jlama.model.AbstractModel.batchForward(AbstractModel.java:270)
	at com.github.tjake.jlama.model.AbstractModel.generate(AbstractModel.java:480)
	at com.github.tjake.jlama.cli.commands.ChatCommand.run(ChatCommand.java:92)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	... 9 more

$ java -version
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)
	
$ jbang --version
0.119.0

$ system_profiler SPSoftwareDataType SPHardwareDataType | grep Chip -A 2
Chip: Apple M1 Pro
Total Number of Cores: 8 (6 performance and 2 efficiency)
Memory: 32 GB
```

**Comment by tjake** [comment]
Thanks for the report. I will fix in meantime you can use this model https://huggingface.co/tjake/Llama-3.2-1B-Instruct-Jlama-Q4

**Comment by jolivares** [comment]
Thanks for answering, unfortunately after using `https://huggingface.co/tjake/Llama-3.2-1B-Instruct-Jlama-Q4` same error is thrown
```
$ jbang run jlama@tjake chat tjake/Llama-3.2-1B-Instruct-Jlama-Q4 --auto-download
WARNING: Using incubator modules: jdk.incubator.vector
Using Native SIMD Operations (OffHeap)
Model type = Q4, Working memory type = F32, Quantized memory type = I8

Chatting with tjake/Llama-3.2-1B-Instruct-Jlama-Q4...


You: hi

Jlama: Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.github.tjake.jlama.cli.commands.ChatCommand@4b2bac3f): java.lang.UnsupportedOperationException
	at picocli.CommandLine.executeUserObject(CommandLine.java:2035)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2264)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2664)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:2599)
	at com.github.tjake.jlama.cli.JlamaCli.main(JlamaCli.java:57)
	at jlama.main(jlama.java:22)
Caused by: java.lang.UnsupportedOperationException
	at com.github.tjake.jlama.tensor.operations.PanamaTensorOperations.accumulate(PanamaTensorOperations.java:2170)
	at com.github.tjake.jlama.tensor.operations.NativeTensorOperations.accumulate(NativeTensorOperations.java:409)
	at com.github.tjake.jlama.model.TransformerBlock.forward(TransformerBlock.java:185)
	at com.github.tjake.jlama.model.AbstractModel.forward(AbstractModel.java:299)
	at com.github.tjake.jlama.model.AbstractModel.batchForward(AbstractModel.java:286)
	at com.github.tjake.jlama.model.AbstractModel.batchForward(AbstractModel.java:276)
	at com.github.tjake.jlama.model.AbstractModel.generate(AbstractModel.java:541)
	at com.github.tjake.jlama.cli.commands.ChatCommand.run(ChatCommand.java:92)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	... 9 more
```
Also tested your branch [arm-accumulate](https://github.com/tjake/Jlama/tree/arm-accumulate) and it fails in a different place (not sure if it is a WIP, though):
```
$ (arm-accumulate)> ./run-cli.sh chat tjake/Llama-3.2-1B-Instruct-Jlama-Q4 --auto-download
1 compiler directives added
WARNING: Using incubator modules: jdk.incubator.vector
Native operations not available. Consider adding 'com.github.tjake:jlama-native' to the classpath
Using Panama Vector Operations (OffHeap)
Model type = Q4, Working memory type = F32, Quantized memory type = I8

Chatting with tjake/Llama-3.2-1B-Instruct-Jlama-Q4...


You: hi

Jlama: Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.github.tjake.jlama.cli.commands.ChatCommand@7b9a4292): java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException: ARM_128
        at picocli.CommandLine.executeUserObject(CommandLine.java:2035)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2264)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2664)
        at picocli.CommandLine.parseWithHandler(CommandLine.java:2599)
        at com.github.tjake.jlama.cli.JlamaCli.main(JlamaCli.java:57)
Caused by: java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException: ARM_128
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
        at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:653)
        at com.github.tjake.jlama.util.PhysicalCoreExecutor.execute(PhysicalCoreExecutor.java:55)
        at com.github.tjake.jlama.math.VectorMath.pchunk(VectorMath.java:56)
        at com.github.tjake.jlama.model.AbstractModel.sample(AbstractModel.java:426)
        at com.github.tjake.jlama.model.AbstractModel.generate(AbstractModel.java:560)
        at com.github.tjake.jlama.cli.commands.ChatCommand.run(ChatCommand.java:92)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        ... 8 more
Caused by: java.lang.UnsupportedOperationException: ARM_128
        at com.github.tjake.jlama.tensor.operations.PanamaTensorOperations.batchDotProduct(PanamaTensorOperations.java:125)
        at com.github.tjake.jlama.tensor.operations.TensorOperations.dotProductChunk(TensorOperations.java:76)
        at com.github.tjake.jlama.model.AbstractModel.lambda$sample$4(AbstractModel.java:428)
        at com.github.tjake.jlama.math.VectorMath.lambda$pchunk$1(VectorMath.java:60)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:205)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
        at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:189)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.IntPipeline.forEach(IntPipeline.java:463)
        at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:620)
        at com.github.tjake.jlama.math.VectorMath.lambda$pchunk$2(VectorMath.java:59)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
