### ISSUE TITLE
Mac m3 - java.lang.UnsupportedOperationException: ARM_128

### ISSUE THREAD

**Issue by sshaaf** [tjake/Jlama#112]
I am getting unsupported exception while running examples from @mariofusco's [demo](https://github.com/mariofusco/quarkus-drools-llm/tree/jlama-no-rules) 

Stack trace: 
```
Caused by: java.lang.UnsupportedOperationException: ARM_128
        at com.github.tjake.jlama.tensor.operations.PanamaTensorOperations.batchDotProduct(PanamaTensorOperations.java:125)
        at com.github.tjake.jlama.tensor.operations.TensorOperations.dotProductChunk(TensorOperations.java:76)
        at com.github.tjake.jlama.model.AbstractModel.lambda$sample$4(AbstractModel.java:423)
        at com.github.tjake.jlama.math.VectorMath.lambda$pchunk$1(VectorMath.java:60)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:205)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
        at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:189)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.IntPipeline.forEach(IntPipeline.java:463)
        at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:620)
        at com.github.tjake.jlama.math.VectorMath.lambda$pchunk$2(VectorMath.java:59)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

Hardware: Mac M3

**Comment by mariofusco** [comment]
@tjake Just to clarify, as discussed in another issue I made a version of my demo application that doesn't use Drools and put it in the branch linked by @sshaaf, so also others could give it a try. The demo works fine on my Lenovo, but on @sshaaf's Mac M3 machine it throws the execption that he reported here.

**Comment by tjake** [comment]
Are you using the latest version?

**Comment by mariofusco** [comment]
> Are you using the latest version?

Yes https://github.com/mariofusco/quarkus-drools-llm/blob/98490efb1bc805738f10e0f06d0fb28d5795ae62/pom.xml#L16

**Comment by mariofusco** [comment]
Sorry, I think i just found it, the classifier is wrong isn't it? :( https://github.com/mariofusco/quarkus-drools-llm/blob/98490efb1bc805738f10e0f06d0fb28d5795ae62/pom.xml#L60

**Comment by mariofusco** [comment]
> Sorry, I think i just found it, the classifier is wrong isn't it? :( https://github.com/mariofusco/quarkus-drools-llm/blob/98490efb1bc805738f10e0f06d0fb28d5795ae62/pom.xml#L60 /cc @sshaaf

**Comment by mariofusco** [comment]
@tjake we confirm that the problem was in the wrong classifier, please feel free to close this issue and sorry again.

**Comment by wl4g** [comment]
> [@tjake](https://github.com/tjake) we confirm that the problem was in the wrong classifier, please feel free to close this issue and sorry again.

Hello, I have the same error on M3, how did you solve it? It seems that there is no macos_aarm64 library?

**Comment by tjake** [comment]
Take a look at https://github.com/tjake/Jlama/issues/68
