### ISSUE TITLE
JLama not working on Docker with a Mac host.

### ISSUE THREAD

**Issue by toniton** [tjake/Jlama#123]
I get an IndexOutOfBoundsException when trying to run JLama in a Docker environment on my Macbook M1, and there seems to be very little documentation on how to implement this properly. 

Is there a way I can get this running on a Macbook locally?

## Code snippet:
```java
public class SseResourceJLamaResource {

    private final ExecutorService executor = Executors.newCachedThreadPool();

    @GET
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public void streamEvents(@Context SseEventSink eventSink, @Context Sse sse) throws IOException {
        String modelName = "tjake/Llama-3.2-1B-Instruct-JQ4";

        InMemoryEmbeddingStore<TextSegment> embeddingStore = new InMemoryEmbeddingStore<>();
        EmbeddingModel embeddingModel = JlamaEmbeddingModel.builder()
                .modelName(modelName)
                .build();

        TextSegment segment1 = TextSegment.from("I like football.");
        Embedding embedding1 = embeddingModel.embed(segment1).content();
        embeddingStore.add(embedding1, segment1);

        TextSegment segment2 = TextSegment.from("The weather is good today.");
        Embedding embedding2 = embeddingModel.embed(segment2).content();
        embeddingStore.add(embedding2, segment2);

        ContentRetriever contentRetriever = new EmbeddingStoreContentRetriever(embeddingStore, embeddingModel);

        JlamaChatModel m = JlamaChatModel.builder().modelName(modelName)
                .maxTokens(1000)
                .workingQuantizedType(DType.BF16)
                .build();
        Assistant assistant = AiServices.builder(Assistant.class)
                .chatLanguageModel(m)
                .contentRetriever(contentRetriever)
                .build();

        // Open a new thread to handle the event stream
        executor.submit(() -> {
            try (eventSink) {
                // Send periodic events
                    OutboundSseEvent event = sse.newEventBuilder()
                            .name("message")
                            .data(String.class, "Event " + i + assistant.chat("What is my fav sport?"))
                            .build();
            } catch (Exception e) {
                e.printStackTrace();
            }
        });
    }
}
```

## Docker configuration:

```Dockerfile
FROM --platform=linux/amd64 amazoncorretto:21-al2023-jdk
LABEL authors="toni"

EXPOSE 8080 8080

RUN yum update && yum install -y glibc
RUN ldd --version

RUN mkdir app

COPY target/rag-sse-1.0-SNAPSHOT.jar app
COPY config.yml app

WORKDIR app

CMD ["java","--add-modules","jdk.incubator.vector","-jar","rag-sse-1.0-SNAPSHOT.jar","server","config.yml"]
```

## POM looks like:
```xml
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j</artifactId>
            <version>0.36.2</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-embeddings</artifactId>
            <version>0.36.2</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-embeddings-all-minilm-l6-v2</artifactId>
            <version>0.36.2</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-easy-rag</artifactId>
            <version>0.36.2</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-jlama</artifactId>
            <version>0.36.2</version>
        </dependency>
        <dependency>
            <groupId>com.github.tjake</groupId>
            <artifactId>jlama-native</artifactId>
            <!-- for faster inference. supports linux-x86_64, macos-x86_64/aarch_64, windows-x86_64
               Use https://github.com/trustin/os-maven-plugin to detect os and arch -->
            <!--            <classifier>${os.detected.name}-${os.detected.arch}</classifier>-->
            <classifier>linux-x86_64</classifier>
            <version>0.2.1</version> <!-- Version from langchain4j-jlama pom -->
        </dependency>
        ...
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>16</source>
                    <target>16</target>
                    <compilerArgs>
                        <arg>--add-modules</arg>
                        <arg>jdk.incubator.vector</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>--add-modules jdk.incubator.vector</argLine>
                </configuration>
            </plugin>
          ...
```

## Console output:
```bash
INFO  [2024-11-24 18:58:40,445] org.eclipse.jetty.server.Server: Started Server@263bbfeb{STARTING}[11.0.24,sto=30000] @8241ms
2024-11-24T18:58:54.997524376Z INFO  [2024-11-24 18:58:54,994] ai.djl.util.Platform: Found matching platform from: jar:file:/app/rag-sse-1.0-SNAPSHOT.jar!/native/lib/tokenizers.properties
2024-11-24T18:58:55.001262917Z INFO  [2024-11-24 18:58:55,000] ai.djl.huggingface.tokenizers.jni.LibUtils: Extracting native/lib/linux-x86_64/cpu/libtokenizers.so to cache ...
2024-11-24T18:58:56.884779835Z INFO  [2024-11-24 18:58:56,880] com.github.tjake.jlama.util.HttpSupport: Downloading file: /root/.jlama/models/tjake_Llama-3.2-1B-Instruct-JQ4/README.md
2024-11-24T18:58:56.934044668Z INFO  [2024-11-24 18:58:56,911] com.github.tjake.jlama.util.HttpSupport: Downloaded file: /root/.jlama/models/tjake_Llama-3.2-1B-Instruct-JQ4/README.md
2024-11-24T18:58:57.100072543Z INFO  [2024-11-24 18:58:57,099] com.github.tjake.jlama.util.HttpSupport: Downloading file: /root/.jlama/models/tjake_Llama-3.2-1B-Instruct-JQ4/config.json
2024-11-24T18:58:57.101510502Z INFO  [2024-11-24 18:58:57,100] com.github.tjake.jlama.util.HttpSupport: Downloaded file: /root/.jlama/models/tjake_Llama-3.2-1B-Instruct-JQ4/config.json
2024-11-24T18:58:57.709544252Z INFO  [2024-11-24 18:58:57,706] com.github.tjake.jlama.util.HttpSupport: Downloading file: /root/.jlama/models/tjake_Llama-3.2-1B-Instruct-JQ4/model.safetensors
2024-11-24T18:59:22.879697250Z INFO  [2024-11-24 18:59:22,871] com.github.tjake.jlama.util.HttpSupport: Downloaded file: /root/.jlama/models/tjake_Llama-3.2-1B-Instruct-JQ4/model.safetensors
2024-11-24T18:59:23.175065458Z INFO  [2024-11-24 18:59:23,173] com.github.tjake.jlama.util.HttpSupport: Downloading file: /root/.jlama/models/tjake_Llama-3.2-1B-Instruct-JQ4/tokenizer.json
2024-11-24T18:59:23.637505417Z INFO  [2024-11-24 18:59:23,634] com.github.tjake.jlama.util.HttpSupport: Downloaded file: /root/.jlama/models/tjake_Llama-3.2-1B-Instruct-JQ4/tokenizer.json
2024-11-24T18:59:23.788288125Z INFO  [2024-11-24 18:59:23,787] com.github.tjake.jlama.util.HttpSupport: Downloading file: /root/.jlama/models/tjake_Llama-3.2-1B-Instruct-JQ4/tokenizer_config.json
2024-11-24T18:59:23.798422583Z INFO  [2024-11-24 18:59:23,793] com.github.tjake.jlama.util.HttpSupport: Downloaded file: /root/.jlama/models/tjake_Llama-3.2-1B-Instruct-JQ4/tokenizer_config.json
2024-11-24T18:59:29.429516794Z WARN  [2024-11-24 18:59:29,424] com.github.tjake.jlama.tensor.operations.TensorOperationsProvider: Native operations not available. Consider adding 'com.github.tjake:jlama-native' to the classpath
2024-11-24T18:59:29.462436211Z WARN  [2024-11-24 18:59:29,460] com.github.tjake.jlama.util.MachineSpec: Unknown vector type: 128
2024-11-24T18:59:29.463126669Z INFO  [2024-11-24 18:59:29,462] com.github.tjake.jlama.tensor.operations.TensorOperationsProvider: Using Naive Java Operations (OffHeap)
2024-11-24T18:59:29.463458794Z WARN  [2024-11-24 18:59:29,463] com.github.tjake.jlama.model.AbstractModel: Quantized memory type I16 not supported, falling back to F32
2024-11-24T18:59:29.466228961Z INFO  [2024-11-24 18:59:29,464] com.github.tjake.jlama.model.AbstractModel: Model type = Q4, Working memory type = F32, Quantized memory type = F32
2024-11-24T18:59:30.245937003Z java.lang.IndexOutOfBoundsException
2024-11-24T18:59:30.251008045Z 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
2024-11-24T18:59:30.251284503Z 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
2024-11-24T18:59:30.251293503Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
2024-11-24T18:59:30.251822920Z 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542)
2024-11-24T18:59:30.251829045Z 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
2024-11-24T18:59:30.251830753Z 	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:653)
2024-11-24T18:59:30.251832253Z 	at com.github.tjake.jlama.util.PhysicalCoreExecutor.execute(PhysicalCoreExecutor.java:55)
2024-11-24T18:59:30.251833753Z 	at com.github.tjake.jlama.math.VectorMath.pchunk(VectorMath.java:56)
2024-11-24T18:59:30.251835170Z 	at com.github.tjake.jlama.model.CausalSelfAttention.forward(CausalSelfAttention.java:157)
2024-11-24T18:59:30.251836753Z 	at com.github.tjake.jlama.model.TransformerBlock.forward(TransformerBlock.java:173)
2024-11-24T18:59:30.251838211Z 	at com.github.tjake.jlama.model.AbstractModel.forward(AbstractModel.java:299)
2024-11-24T18:59:30.251839628Z 	at com.github.tjake.jlama.model.AbstractModel.batchForward(AbstractModel.java:286)
2024-11-24T18:59:30.251841086Z 	at com.github.tjake.jlama.model.AbstractModel.batchForward(AbstractModel.java:276)
2024-11-24T18:59:30.251842503Z 	at com.github.tjake.jlama.model.AbstractModel.generate(AbstractModel.java:541)
2024-11-24T18:59:30.251843920Z 	at dev.langchain4j.model.jlama.JlamaChatModel.generate(JlamaChatModel.java:117)
2024-11-24T18:59:30.251875961Z 	at dev.langchain4j.model.jlama.JlamaChatModel.generate(JlamaChatModel.java:70)
2024-11-24T18:59:30.251879003Z 	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:228)
2024-11-24T18:59:30.251880586Z 	at jdk.proxy2/jdk.proxy2.$Proxy63.chat(Unknown Source)
2024-11-24T18:59:30.251882045Z 	at org.toniton.sse.SseResourceJLamaResource.lambda$streamEvents$0(SseResourceJLamaResource.java:64)
2024-11-24T18:59:30.251883628Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
2024-11-24T18:59:30.251885045Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
2024-11-24T18:59:30.251886503Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-11-24T18:59:30.251887961Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-11-24T18:59:30.251889503Z 	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-11-24T18:59:30.259313628Z Caused by: java.lang.IndexOutOfBoundsException
2024-11-24T18:59:30.259346086Z 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
2024-11-24T18:59:30.259349961Z 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
2024-11-24T18:59:30.259351628Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
2024-11-24T18:59:30.259353128Z 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542)
2024-11-24T18:59:30.259354670Z 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
2024-11-24T18:59:30.259356170Z 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670)
2024-11-24T18:59:30.259357628Z 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
2024-11-24T18:59:30.259359170Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:189)
2024-11-24T18:59:30.259360670Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
2024-11-24T18:59:30.259362170Z 	at java.base/java.util.stream.IntPipeline.forEach(IntPipeline.java:463)
2024-11-24T18:59:30.259363628Z 	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:620)
2024-11-24T18:59:30.259365045Z 	at com.github.tjake.jlama.math.VectorMath.lambda$pchunk$2(VectorMath.java:59)
2024-11-24T18:59:30.259366503Z 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403)
2024-11-24T18:59:30.259368003Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
2024-11-24T18:59:30.259369378Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
2024-11-24T18:59:30.259370878Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
2024-11-24T18:59:30.259382878Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
2024-11-24T18:59:30.259384420Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2024-11-24T18:59:30.259385920Z Caused by: java.lang.IndexOutOfBoundsException: Range [32768, 32768 + 131072) out of bounds for length 131072
2024-11-24T18:59:30.259387503Z 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
2024-11-24T18:59:30.259388878Z 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:118)
2024-11-24T18:59:30.259390420Z 	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:397)
2024-11-24T18:59:30.259393003Z 	at java.base/java.util.Objects.checkFromIndexSize(Objects.java:437)
2024-11-24T18:59:30.259394461Z 	at java.base/java.nio.DirectFloatBufferRU.slice(DirectFloatBufferRU.java:269)
2024-11-24T18:59:30.259395836Z 	at com.github.tjake.jlama.tensor.FloatBufferTensor.make(FloatBufferTensor.java:100)
2024-11-24T18:59:30.259397295Z 	at com.github.tjake.jlama.tensor.Q4ByteBufferTensor.make(Q4ByteBufferTensor.java:169)
2024-11-24T18:59:30.259398753Z 	at com.github.tjake.jlama.tensor.AbstractTensor.slice(AbstractTensor.java:130)
2024-11-24T18:59:30.259400128Z 	at com.github.tjake.jlama.tensor.AbstractTensor.slice(AbstractTensor.java:102)
2024-11-24T18:59:30.259401545Z 	at com.github.tjake.jlama.tensor.operations.NaiveTensorOperations.batchDotProduct(NaiveTensorOperations.java:91)
2024-11-24T18:59:30.259403086Z 	at com.github.tjake.jlama.tensor.operations.TensorOperations.dotProductChunk(TensorOperations.java:76)
2024-11-24T18:59:30.259404545Z 	at com.github.tjake.jlama.model.CausalSelfAttention.lambda$forward$0(CausalSelfAttention.java:159)
2024-11-24T18:59:30.259406003Z 	at com.github.tjake.jlama.math.VectorMath.lambda$pchunk$1(VectorMath.java:60)
2024-11-24T18:59:30.259407461Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:205)
2024-11-24T18:59:30.259408878Z 	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
2024-11-24T18:59:30.259410336Z 	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
2024-11-24T18:59:30.259411753Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2024-11-24T18:59:30.259413170Z 	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
2024-11-24T18:59:30.259414586Z 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
```

**Comment by tjake** [comment]
Hello,

This looks like the main issue is the mac running as amd64 uses a 128 bit vector which isn't supported for non-arm.  

```
2024-11-24T18:59:29.462436211Z WARN  [2024-11-24 18:59:29,460] com.github.tjake.jlama.util.MachineSpec: Unknown vector type: 128
```

Is there a reason you're using amd64 build vs arm?

**Comment by toniton** [comment]
Hi. Thanks for the prompt response.

No specific reasons, I could've understood the configuration wrongly, my Mac is an **M1**, and it runs on **ARM64**, but due to the supported versions of `jlama-native`, I had to setup Docker to **AMD64**, so I can set the version for `jlama-native` to `<classifier>linux-x86_64</classifier>` in my POM.

**Comment by toniton** [comment]
Leaving this here, could be helpful for someone else in the future.
I managed to get this to work on my M1. I switched the  to use `<classifier>aarch</classifier>` and used **I18** as the quantized configuration. The model I ended up using for this was the **"tjake/TinyLlama-1.1B-Chat-v1.0-Jlama-Q4"**.

**Comment by toniton** [comment]
On intellij, I also add to add the following extra arguments: `--add-modules jdk.incubator.vector --enable-native-access ALL-UNNAMED --enable-preview` for my run function to work.
<img width="1023" alt="Screenshot 2024-11-27 at 21 09 13" src="https://github.com/user-attachments/assets/733bd25e-11d7-4830-a48a-96756dac1b7f">

**Comment by toniton** [comment]
Full code example here: https://github.com/toniton/rag-sse-example

**Comment by tjake** [comment]
Great glad you figured it out.  BTW, you should use https://huggingface.co/tjake/Llama-3.2-1B-Instruct-JQ4

**Comment by toniton** [comment]
Thanks, I'll use that 🙏
