### ISSUE TITLE
File model.safetensors.index.json  not found

### ISSUE THREAD

**Issue by asad-awadia** [tjake/Jlama#2]
I downloaded the model directly from meta's repo not hugging face but the code is looking for a file called

`model.safetensors.index.json` when opening with `loadWithWeights`

But I do not have this file? Where is this coming from? There is a file called params.json ```{"dim": 4096, "multiple_of": 256, "n_heads": 32, "n_layers": 32, "norm_eps": 1e-06, "vocab_size": -1}```

is that the same?

**Comment by asad-awadia** [comment]
also not sure what this config.json file is? is this code specifically for the format downloaded from hugging face?

**Comment by asad-awadia** [comment]
Using the HF 7B chat model I am getting

```
Exception in thread "main" java.lang.IllegalArgumentException: Out of range: 2336927755350992246
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:204)
	at com.google.common.primitives.Ints.checkedCast(Ints.java:89)
	at com.github.tjake.jlama.safetensors.SafeTensors.readTensorInfoMap(SafeTensors.java:19)
	at com.github.tjake.jlama.safetensors.SafeTensorIndex.loadWithWeights(SafeTensorIndex.java:67)
```

**Comment by tjake** [comment]
Yes you need to use the download_model.sh script to get all the necessary files from hugging face. config.json generated by hugging face models.

**Comment by tjake** [comment]
This only works on hugging face safe tensor models.  I can include a script to generate safe tensors from any other format, though just getting the model from HF is easier
