### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by maxbrito500** [tjake/Jlama#50]
Hello Jake, 

Thank you for sharing this tool, looked fantastically simple. Specially appreciated the support for previous JDK since using the latest/greatest is always a difficulty on the server domain.

Was downloading and running for a local test. I'm running the sample which downloaded the data model fine but then got stuck on this error:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.github.tjake.jlama.model.ModelSupport.loadModel(ModelSupport.java:161)
	at com.github.tjake.jlama.model.ModelSupport.loadModel(ModelSupport.java:87)
	at com.github.tjake.jlama.model.ModelSupport.loadModel(ModelSupport.java:77)
	at nostrium.chat1.Chat1.sample(Chat1.java:36)
	at nostrium.chat1.Chat1.main(Chat1.java:61)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at com.github.tjake.jlama.model.ModelSupport.loadModel(ModelSupport.java:153)
	... 4 more
Caused by: java.lang.NoClassDefFoundError: jdk/incubator/vector/Vector
	at com.github.tjake.jlama.tensor.TensorCache.get(TensorCache.java:82)
	at com.github.tjake.jlama.model.AbstractModel.makeTensor(AbstractModel.java:187)
	at com.github.tjake.jlama.model.AbstractModel.<init>(AbstractModel.java:128)
	at com.github.tjake.jlama.model.llama.LlamaModel.<init>(LlamaModel.java:55)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 7 more
Caused by: java.lang.ClassNotFoundException: jdk.incubator.vector.Vector
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 12 more
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:1000)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:947)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:471)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
```
Work conditions: Ubuntu x64 with Netbeans IDE. 

I've upgraded the JDK to 22, set the language for 21. Then was trying to set the parameters on the maven configuration itself:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>nostrium</groupId>
    <artifactId>chat1</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <exec.mainClass>nostrium.chat1.Chat1</exec.mainClass>
    </properties>
    
    <build>
        <plugins>
            <!-- Add maven-compiler-plugin with a specified version -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version> <!-- Set the plugin version here -->
                <configuration>
                    <source>21</source>
                    <target>21</target>
                    <compilerArgs combine.children="append">
                        <arg>--add-exports=java.base/sun.net.util=ALL-UNNAMED</arg>
                        <arg>--add-exports=java.management/sun.management=ALL-UNNAMED</arg>
                        <arg>--add-exports=java.rmi/sun.rmi.registry=ALL-UNNAMED</arg>
                        <arg>--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED</arg>
                        <arg>--add-modules=jdk.incubator.vector</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            
            <!-- Optionally, you can also configure the exec-maven-plugin here if needed for running the project -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <mainClass>${exec.mainClass}</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.github.tjake</groupId>
            <artifactId>jlama-core</artifactId>
            <version>0.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.tjake</groupId>
            <artifactId>jlama-native</artifactId>
            <classifier>linux-x86_64</classifier>
            <version>0.3.1</version>
        </dependency>
    </dependencies>
</project>


```

Work conditions are Ubuntu on x64 CPU with Netbeans IDE. I've tried different combinations of JDK up to version 22, modified the pom.xml to load the flags as you can see. Was looking online on the web and here on the issues, but still clueless on how this can be solved.

Do you have an idea how to get it solved?

Many thanks in advance.

**Comment by tjake** [comment]
Hi,

Looks like you aren't passing the vector module flag in your exec call:

Add the following like this:

https://github.com/langchain4j/langchain4j-examples/blob/main/jlama-examples/pom.xml#L73

**Comment by maxbrito500** [comment]
Thank you for the quick reply, was about to give up when you answered.

Adding those lines to the pom.xml didn't help. I've later downloaded the whole langchain4j to specifically run the examples with that pom.xml and result was the same.

Eventually came to the conclusion of adding it on the vm arguments when pressing the "play" button and that finally worked. Still have no clue with the langchain pom.xml holds the same results but this situation makes testing and overall launching of the app way more difficult.

Last question, why is it necessary to know the architecture on maven? Isn't JLama 100% java code that is portable?

Many thanks.

**Comment by tjake** [comment]
> Still have no clue with the langchain pom.xml holds the same results but this situation makes testing and overall launching of the app way more difficult.

Once the vector extensions come out of incubation it'll be simpler but for now yeah its annoying.

> Last question, why is it necessary to know the architecture on maven? Isn't JLama 100% java code that is portable?

You can run jlama without the native module but it runs faster with the native module (only for matrix multiplication)

**Comment by maxbrito500** [comment]
Thank you for the complete reply and quick attention. Will support and promote JLama as much as possible, very good library.
