### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant com.github.tjake.jlama.model.ModelSupport.ModelType.QWEN2

### ISSUE THREAD

**Issue by urbandroid** [tjake/Jlama#67]
1.jlama restapi NTQAI/Nxcode-CQ-7B-orpo --auto-download

Here is the result:

`jlama restapi NTQAI/Nxcode-CQ-7B-orpo --auto-download
NOTE: Picked up JDK_JAVA_OPTIONS: --add-modules jdk.incubator.vector --enable-preview
WARNING: Using incubator modules: jdk.incubator.vector
NOTE: Picked up JDK_JAVA_OPTIONS: --add-modules jdk.incubator.vector --enable-preview
WARNING: Using incubator modules: jdk.incubator.vector
java.lang.IllegalArgumentException: No enum constant com.github.tjake.jlama.model.ModelSupport.ModelType.QWEN2
	at java.base/java.lang.Enum.valueOf(Enum.java:293)
	at com.github.tjake.jlama.model.ModelSupport$ModelType.valueOf(ModelSupport.java:54)
	at com.github.tjake.jlama.safetensors.SafeTensorSupport.detectModel(SafeTensorSupport.java:91)
	at com.github.tjake.jlama.model.ModelSupport.loadModel(ModelSupport.java:172)
	at com.github.tjake.jlama.model.ModelSupport.loadModel(ModelSupport.java:121)
	at com.github.tjake.jlama.cli.commands.ApiServiceCommand.run(ApiServiceCommand.java:69)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2264)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2664)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:2599)
	at com.github.tjake.jlama.cli.JlamaCli.main(JlamaCli.java:57)
	at jlama.main(jlama.java:22)
`

**Comment by tjake** [comment]
Need to add qwen support. i'll add in next week or so

**Comment by lordofthejars** [comment]
Oh yes qwen model is becoming really popular
