### ISSUE TITLE
Using GraalVM seems to make execution super slow

### ISSUE THREAD

**Issue by geoand** [tjake/Jlama#78]
# Description

I am using [this](https://github.com/user-attachments/files/17407750/jllama-ex.zip) simple application that uses Quarkus LangChain4j with Jlama.

When using Java `23-tem` (as seen in sdkman), everything works nice and snappy. 
However, when I run with `23.0.1-graal` the inference seems to slow to a crawl. 

I am pretty sure this isn't a Jlama issue per se, it looks like a GraalVM issue to me, but that's just a  guess

cc @mukel

# How to reproducer

Build using:

```
mvn package -DskipTests
```

Run using:

```
java --add-modules=jdk.incubator.vector --enable-preview -jar target/quarkus-app/quarkus-run.jar
```

**Comment by tjake** [comment]
Yeah this is what I mentioned in my talk about the vector api isn't always made intrinsic on some JVMs.  This is why I've had to rely on the native module for consistency till it's fixed.

```
  java.lang.Thread.State: RUNNABLE
	at jdk.incubator.vector.ShortVector.uOpTemplate(jdk.incubator.vector@23/ShortVector.java:163)
	at jdk.incubator.vector.Short256Vector.uOp(jdk.incubator.vector@23/Short256Vector.java:191)
	at jdk.incubator.vector.Short256Vector.uOp(jdk.incubator.vector@23/Short256Vector.java:41)
	at jdk.incubator.vector.ShortVector.lambda$rearrangeTemplate$62(jdk.incubator.vector@23/ShortVector.java:2408)
	at jdk.incubator.vector.ShortVector$$Lambda/0x00007e7c873fc698.apply(jdk.incubator.vector@23/Unknown Source)
	at jdk.internal.vm.vector.VectorSupport.rearrangeOp(java.base@23/VectorSupport.java:605)
	at jdk.incubator.vector.ShortVector.rearrangeTemplate(jdk.incubator.vector@23/ShortVector.java:2405)
	at jdk.incubator.vector.Short256Vector.rearrange(jdk.incubator.vector@23/Short256Vector.java:452)
	at jdk.incubator.vector.Short256Vector.rearrange(jdk.incubator.vector@23/Short256Vector.java:41)
	at jdk.incubator.vector.ShortVector.sliceTemplate(jdk.incubator.vector@23/ShortVector.java:2320)
	at jdk.incubator.vector.Short256Vector.slice(jdk.incubator.vector@23/Short256Vector.java:424)
	at jdk.incubator.vector.Short256Vector.slice(jdk.incubator.vector@23/Short256Vector.java:41)
	at jdk.incubator.vector.AbstractVector.convertShapeTemplate(jdk.incubator.vector@23/AbstractVector.java:383)
	at jdk.incubator.vector.Short256Vector.convertShape(jdk.incubator.vector@23/Short256Vector.java:248)
	at com.github.tjake.jlama.tensor.operations.PanamaTensorOperations$GemmerI8Q4_256.lambda$initMatmul1x1$0(PanamaTensorOperations.java:909)
	at com.github.tjake.jlama.tensor.operations.PanamaTensorOperations$GemmerI8Q4_256$$Lambda/0x00007e7c873ae930.accept(Unknown Source)
	at com.github.tjake.jlama.tensor.operations.PanamaTensorOperations$Gemmer.kernel(PanamaTensorOperations.java:1743)
	at com.github.tjake.jlama.tensor.operations.PanamaTensorOperations$GemmerI8Q4_256.pickKernel(PanamaTensorOperations.java:856)
	at com.github.tjake.jlama.tensor.operations.PanamaTensorOperations$Gemmer.mnpack(PanamaTensorOperations.java:1721)
	at com.github.tjake.jlama.tensor.operations.PanamaTensorOperations$Gemmer.matmul(PanamaTensorOperations.java:1715)
	at com.github.tjake.jlama.tensor.operations.PanamaTensorOperations.batchDotProduct(PanamaTensorOperations.java:145)
	at com.github.tjake.jlama.tensor.operations.TensorOperations.dotProductChunk(TensorOperations.java:76)
	at com.github.tjake.jlama.tensor.operations.TensorOperations.dotProductBatchChunk(TensorOperations.java:90)
	at com.github.tjake.jlama.model.MLPBlock.lambda$forward$0(MLPBlock.java:113)
	at com.github.tjake.jlama.model.MLPBlock$$Lambda/0x00007e7c87436b40.accept(Unknown Source)
	at com.github.tjake.jlama.math.VectorMath.lambda$pchunk$1(VectorMath.java:58)
	at com.github.tjake.jlama.math.VectorMath$$Lambda/0x00007e7c873ae4d0.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(java.base@23/ForEachOps.java:205)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(java.base@23/Streams.java:104)
	at java.util.Spliterator$OfInt.forEachRemaining(java.base@23/Spliterator.java:712)
	at java.util.stream.AbstractPipeline.copyInto(java.base@23/AbstractPipeline.java:570)
	at java.util.stream.ForEachOps$ForEachTask.compute(java.base@23/ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(java.base@23/CountedCompleter.java:759)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@23/ForkJoinTask.java:507)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@23/ForkJoinPool.java:1458)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@23/ForkJoinPool.java:2034)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@23/ForkJoinWorkerThread.java:189)
```

**Comment by geoand** [comment]
Ah, missed that details, thanks!

**Comment by tjake** [comment]
It would be awesome if @mukel and the graalvm team could take a look since this reproduces so easily here.
