### ISSUE TITLE
JlamaStreamingChatModel does not support tools

### ISSUE THREAD

**Issue by ricoapon** [tjake/Jlama#94]
# Problem
JLama indicated that it supports the use of tools for (some) models. I have used `tjake/Llama-3.2-1B-Instruct-JQ4`, and that does indeed support tools.

However, when I try to use streaming for this model, it doesn't seem to support tools. This seems to be library issue and not model issue. I am not sure if it is correct to expect that streaming is supported for tools, but I would think it is.

# Versions
I am using langchain4j 0.35.0 and jlama 0.7.0.

# Reproduction path

```
import dev.langchain4j.agent.tool.Tool;
import dev.langchain4j.model.chat.ChatLanguageModel;
import dev.langchain4j.model.chat.StreamingChatLanguageModel;
import dev.langchain4j.model.jlama.JlamaChatModel;
import dev.langchain4j.model.jlama.JlamaStreamingChatModel;
import dev.langchain4j.service.AiServices;
import dev.langchain4j.service.Result;
import dev.langchain4j.service.TokenStream;

public class Main {
    public static void main() {
        String modelName = "tjake/Llama-3.2-1B-Instruct-JQ4";
        String prompt = """
                What is the square root of 1244?
                """.trim();

        System.out.println(promptModelUsingLangchain(prompt, modelName));
    }

    interface Assistant {
        TokenStream chat(String userMessage);
    }

    private static String promptModelUsingLangchain(String prompt, String modelName) {
        StreamingChatLanguageModel model = JlamaStreamingChatModel.builder()
                .modelName(modelName)
                .build();

        Assistant assistant = AiServices.builder(Assistant.class)
                .streamingChatLanguageModel(model)
                .tools(new MyTools())
                .build();

        TokenStream tokenStream = assistant.chat(prompt);
        tokenStream.onNext(System.out::println)
                .onComplete(System.out::println)
                .onError(Throwable::printStackTrace)
                .start();

        return "this line is never reached";
    }

    static class MyTools {
        @Tool
        int add(int a, int b) {
            System.out.println("Method was called with " + a + ", " + b);
            return a + b;
        }

        @Tool
        public double squareRoot(double x) {
            System.out.println("Method was called with " + x);
            return Math.sqrt(x);
        }
    }
}
```

Output:
```
[main] INFO com.github.tjake.jlama.tensor.operations.TensorOperationsProvider - Using Native SIMD Operations (OffHeap)
[main] INFO com.github.tjake.jlama.model.AbstractModel - Model type = Q4, Working memory type = F32, Quantized memory type = I8
Exception in thread "main" java.lang.IllegalArgumentException: Tools are currently not supported by this model
	at dev.langchain4j.model.chat.StreamingChatLanguageModel.generate(StreamingChatLanguageModel.java:61)
	at dev.langchain4j.service.AiServiceTokenStream.start(AiServiceTokenStream.java:116)
	at com.keylane.rapon.Main.promptModelUsingLangchain(Main.java:40)
	at com.keylane.rapon.Main.main(Main.java:19)
```

**Comment by tjake** [comment]
Hello!

Yes I need to fix this, I only added it for the non-streaming version.  I think the issue is to know when to not stream because the model is making a function call output (this should be hidden).  A user will only want to see the result of the model before and after the function call.

**Comment by LiveNathan** [comment]
The workaround for now is to use the non-streaming model?

**Comment by tjake** [comment]
Yes, I'm not aware of another implementation that handles streaming chat with tool calls?  It's a tricky problem

**Comment by tjake** [comment]
Yeah I mean an oss tool like ollama.  I think what you would do is stream until you see a special token then progressively try to parse json and when closed execute the call

**Comment by LiveNathan** [comment]
You may want to see [this conversation](https://github.com/langchain4j/langchain4j/discussions/2088#discussioncomment-11251382).

**Comment by tjake** [comment]
Ah cool, I see localAI supports it I can see what they do and add it, thx!

**Comment by tjake** [comment]
https://github.com/langchain4j/langchain4j/pull/2181

**Comment by LiveNathan** [comment]
Great! So for me to be able to use this, I need to wait for the next version of Langchain4j to come out or just update to the latest version of Jlama?

**Comment by tjake** [comment]
Next langchain4j
