### ISSUE TITLE
langchain4j example JlamaAiFunctionCallingExamples doesn't work with version 0.7

### ISSUE THREAD

**Issue by arxx-opus** [tjake/Jlama#95]
# Exception running langchain4j example JlamaAiFunctionCallingExamples with JLama  version 0.7 

    Exception in thread "main" java.lang.ClassCastException: class [Lcom.github.tjake.jlama.safetensors.prompt.ToolCall; cannot be cast to class java.util.List ([Lcom.github.tjake.jlama.safetensors.prompt.ToolCall; is in unnamed module of loader 'app'; java.util.List is in module java.base of loader 'bootstrap')
	    at com.github.tjake.jlama.model.AbstractModel.postProcessResponse(AbstractModel.java:597)
	    at com.github.tjake.jlama.model.AbstractModel.generate(AbstractModel.java:557)
	    at dev.langchain4j.model.jlama.JlamaChatModel.generate(JlamaChatModel.java:117)
	    at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:229)
	    at $Proxy17.chat(Unknown Source)
	    at JlamaAiFunctionCallingExamples$Payment_Data_From_AiServices.main(JlamaAiFunctionCallingExamples.java:60)

JsonSupport.om readValue() returns a Tool instead of List of Tool

List<ToolCall> toolCallList = JsonSupport.om.readValue(jsonCall, ToolCall.toolCallListTypeReference);

**Comment by gschrader** [comment]
This still fails with the same exception for me in version 0.8.2

**Comment by tjake** [comment]
Are you using latest langchain4j?

**Comment by gschrader** [comment]
I've tried 0.36.0, I see there is a 0.36.1 now, I can try that as well

**Comment by tjake** [comment]
If I want to reproduce I just rub the examples or are you using something g else?

**Comment by gschrader** [comment]
yes I've just copy/pasted the example, pretty sure my dependencies are ok.

The readValue call is returning an array not a List:

![image](https://github.com/user-attachments/assets/5006fd85-3a05-4ac3-936a-bb0fe26c494a)

**Comment by gschrader** [comment]
This code would work:

```
            List<ToolCall> toolCallList = JsonSupport.om.readValue(jsonCall, new TypeReference<>() {});
````
